/*
 * This source file was generated by the Gradle 'init' task
 */
package mine;

import mine.Engine.EngineManager;
import mine.Engine.Untils.PerlinNoise;
import mine.Engine.WindowManager;

public class App {

    static private WindowManager wnm;
    static private EngineManager engine;

    public static void main(String[] args) {
        wnm = new WindowManager("Minecraft", 1920, 1080, false, false);
        wnm.init();
        engine = new EngineManager();
        engine.init();
        engine.run();

        wnm.clear();
    }

    public static WindowManager getWindow() {
        return wnm;
    }
    public static EngineManager getEngine() {
        return engine;
    }
}
